# Ostad Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - name: ostad-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: MONGO_URL
          value: {{ .Values.env.mongoUrl | quote }}
---
# Ostad Server Service
apiVersion: v1
kind: Service
metadata:
  name: ostad-server-service
spec:
  selector:
    app: ostad-server
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
