apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: farhansabbir
data:
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_DB_NAME: "Ostad-DB"
  ME_CONFIG_MONGODB_SERVER: "mongo"
  ME_CONFIG_MONGODB_PORT: "27017"
