apiVersion: v1
kind: Secret
metadata:
  name: ostad-db-secret
  namespace: farhansabbir
type: Opaque
data:
  username: ZmFyaGFuc2FiYmly # base64 encoded "farhansabbir"
  password: b3N0YWQ= # base64 encoded "ostad"
