replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: latest

service:
  port: 27017

volume:
  hostPath: /mnt/mongo-data

env:
  username: ostad
  password: ostad

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"