apiVersion: v1
kind: Service
metadata:
  name: ostad-ui-service
  namespace: farhansabbir
spec:
  selector:
    app: ostad-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
