# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongo.env.username | quote }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongo.env.password | quote }}
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        hostPath:
          path: {{ .Values.mongo.volume.hostPath }}
          type: DirectoryOrCreate
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
