# Mongo Express Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - name: mongo-express
        image: "{{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}"
        imagePullPolicy: {{ .Values.mongoExpress.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongoExpress.service.port }}
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongo"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: {{ .Values.mongo.env.username | quote }}
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: {{ .Values.mongo.env.password | quote }}
---
# Mongo Express Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: {{ .Values.mongoExpress.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.mongoExpress.service.port }}
    targetPort: {{ .Values.mongoExpress.service.port }}
    nodePort: {{ .Values.mongoExpress.service.nodePort }}
