# Ostad Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server-deployment
  labels:
    app: ostad-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - name: ostad-server
        image: "{{ .Values.ostadServer.image.repository }}:{{ .Values.ostadServer.image.tag }}"
        imagePullPolicy: {{ .Values.ostadServer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ostadServer.service.port }}
        env:
        - name: MONGO_URL
          value: "mongodb://{{ .Values.mongo.env.username }}:{{ .Values.mongo.env.password }}@mongo:{{ .Values.mongo.service.port }}"
---
# Ostad Server Service
apiVersion: v1
kind: Service
metadata:
  name: ostad-server-service
spec:
  selector:
    app: ostad-server
  ports:
  - protocol: TCP
    port: {{ .Values.ostadServer.service.port }}
    targetPort: {{ .Values.ostadServer.service.port }}
