name: Docker Image CI for Sonarqube Branch

on:
  push:
    branches: [ "assignment/sonarqube" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository
      run: ls -la

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./next-japan/Dockerfile
        push: true
        tags: farhansabbir/sonarqube-assignment:latest
