apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server-deployment
  labels:
    app: ostad-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      containers:
      - name: ostad-server
        image: farhansabbir/ostad-server
        ports:
        - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: ostad-server-service
spec:
  selector:
    app: ostad-server
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-ui-deployment
  labels:
    app: ostad-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-ui
  template:
    metadata:
      labels:
        app: ostad-ui
    spec:
      containers:
      - name: ostad-ui
        image: farhansabbir/ostad-ui
        ports:
        - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: ostad-ui-service
spec:
  selector:
    app: ostad-ui
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173

# ---
# IMPORTANT: This application requires a MongoDB database.
# The server is configured to connect to a service named 'mongo' on port 27017.
# You will need to deploy MongoDB in your cluster and ensure a service named 'mongo' is available.
# For example, you could use the Bitnami Helm chart to deploy MongoDB:
# helm install my-release bitnami/mongodb --set service.name=mongo
