apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server-deployment
  labels:
    app: ostad-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      containers:
      - name: ostad-server
        # IMPORTANT: Replace this with the actual Docker image name you build and push to a registry.
        image: farhansabbir/ostad-server:latest
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: ostad-server-service
spec:
  selector:
    app: ostad-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5050
