apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server-deployment
  namespace: farhansabbir
  labels:
    app: ostad-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      containers:
      - name: ostad-server
        image: farhansabbir/ostad-server:latest 
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: ostad-db-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ostad-db-secret
              key: password
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB_NAME
          value: Ostad-DB
