apiVersion: v2
name: ostad-umbrella
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: mongo-chart
  version: "0.1.0"
  repository: "file://./charts/mongo-chart"
- name: mongo-express-chart
  version: "0.1.0"
  repository: "file://./charts/mongo-express-chart"
- name: ostad-server-chart
  version: "0.1.0"
  repository: "file://./charts/ostad-server-chart"
- name: ostad-ui-chart
  version: "0.1.0"
  repository: "file://./charts/ostad-ui-chart"