name: Docker Image CI for Sonarqube Branch

on:
  push:
    branches: [ "assignment/sonarqube" ]

jobs:
  build-and-push:
    runs-on: ec2-hosted-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: farhansabbir/nextjs:latest
